language: php
php:
  - '7.1'
  - '7.2'
env:
  - PHPUNIT_VERSION="^7"; PSRSIMPLE_VERSION="^1.0.1"
before_install:
  - sudo add-apt-repository ppa:chris-lea/libsodium;
  - sudo apt-get update && sudo apt-get install libsodium-dev -y
install:
  - composer require phpunit/phpunit:${PHPUNIT_VERSION}
  - composer require psr/simple-cache:${PSRSIMPLE_VERSION}
before_script:
  - pecl install libsodium
script: vendor/bin/phpunit --testdox
