language: php
php:
  - '7.1'
  - '7.2'
env:
  - PHPUNIT_VERSION="^7"
  - PSRSIMPLE_VERSION="^1.0.1"

install:
  - composer require phpunit/phpunit:${PHPUNIT_VERSION}
  - composer require psr/simple-cache:${PSRSIMPLE_VERSION}

script: vendor/bin/phpunit --testdox
